### ISSUE TITLE
Android P Beta Support

### ISSUE THREAD

**Issue by Krisgk1** [calabash/calabash-android#869]
Will we have support for Android P Beta for calabash.Will Calabash community work on this?

Having issues in launching the app using start_test_server_in_background

RuntimeError: java.lang.RuntimeException: java.lang.NoSuchFieldException: No field mMessageQueue in class Landroid/app/Instrumentation; (declaration of 'android.app.Instrumentation' appears in /system/framework/framework.jar)
	at sh.calaba.instrumentationbackend.utils.ActivityLaunchedWaiter.getMessageQueue(ActivityLaunchedWaiter.java:124)
	at sh.calaba.instrumentationbackend.utils.ActivityLaunchedWaiter.<init>(ActivityLaunchedWaiter.java:38)
	at sh.calaba.instrumentationbackend.CalabashInstrumentationApplicationLifeCycle.start(CalabashInstrumentationApplicationLifeCycle.java:39)
	at sh.calaba.instrumentationbackend.HttpTestServerLifeCycle$1.startApplication(HttpTestServerLifeCycle.java:26)
	at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:150)
	at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:487)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchFieldException: No field mMessageQueue in class Landroid/app/Instrumentation; (declaration of 'android.app.Instrumentation' appears in /system/framework/framework.jar)
	at java.lang.Class.getDeclaredField(Native Method)
	at sh.calaba.instrumentationbackend.utils.ActivityLaunchedWaiter.getMessageQueue(ActivityLaunchedWaiter.java:119)
	... 6 more

**Comment by Krisgk1** [comment]
Thank you @jmoody.Will look forward for the fix

**Comment by AndreyMitsyk** [comment]
@Krisgk1 @forcefeeld we released android P (api 28) support. Could you please verify and close this issue?

**Comment by Krisgk1** [comment]
@AndreyMitsyk  irb(main):002:0> start_test_server_in_background
RuntimeError: Calabash Client and Test-server version mismatch.
Client version 0.9.4
Test-server version 0.9.3
Expected Test-server version 0.9.4


Solution:


Run 'reinstall_test_server' to make sure you have the correct version

I deleted the old gem 0.9.3 too and used reinstall_test_server, but still getting the same error

**Comment by AndreyMitsyk** [comment]
@Krisgk1 could you please try to use Client version 0.9.3? This error will be fixed in 0.9.5 AFIAK.

**Comment by Krisgk1** [comment]
@AndreyMitsyk  The 9.3 works fine on Android P.Thank you

But noticed this error while taking screenshots

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: sh/calaba/screenshot/ScreenshotTaker has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0

May be due to am using older version of java ??

**Comment by AndreyMitsyk** [comment]
@Krisgk1 yep. Java 10 required for this gem. This was changed in 9.4 to use java 8 for screenshot tool, but server integration was broken. In 9.5 everything will be ok with java 8.

**Comment by Krisgk1** [comment]
Thank you @AndreyMitsyk .Will watch out for 9.5 gem.Shall close this ticket now
